Metrics/LineLength:
  Max: 100
Metrics/MethodLength:
  Max: 100
Metrics/ModuleLength:
  Max: 300
Metrics/ClassLength:
  Max: 300
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
