version: '3.1'

services:
  ruby-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4567:4567
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    restart: always
